### ISSUE TITLE
Stipend at Walmart as a SDE Intern? 

### ISSUE THREAD

**Issue by 1stdevfriend** [sirilalithaadapa/Interview-Experiences#4]

**Comment by 1stdevfriend** [comment]
@riti2409 @sirilalithaadapa @Adarsh-jaiss

**Comment by Adarsh-jaiss** [comment]
-- Kindly share your experience with us :)

**Comment by 1stdevfriend** [comment]
Oh. I believe there is a misunderstanding. 

I'm basically asking how much stipend are they offering? 

@Adarsh-jaiss

**Comment by 1stdevfriend** [comment]
@Adarsh-jaiss @riti2409 @sirilalithaadapa

**Comment by sirilalithaadapa** [comment]
Actually stipend will not revealed.

**Comment by 1stdevfriend** [comment]
Ahh I understand. 

From their side or yours? @sirilalithaadapa

**Comment by sirilalithaadapa** [comment]
from our side.

**Comment by 1stdevfriend** [comment]
Looks unfair but thanks!
